package:
  name: indexed_gzip
  version: 0.8.4

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

source:
  path: ../

requirements:
  build:
    - python
    - numpy
    - cython
    - setuptools
    - pytest-runner
  run:
    - python


test:
  source_files:
    - conftest.py
  requires:
    - pytest
    - numpy
    - coverage
    - pytest-cov
  imports:
    - indexed_gzip
  commands:
    - python -m pytest -v -s  --pyargs  --cov=indexed_gzip --niters 500 indexed_gzip