package:
  name: indexed_gzip
  version: 0.8.2

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

source:
  path: ../

requirements:
  build:
    - python
    - cython
    - setuptools
    - pytest-runner
  run:
    - python
